name:                server
version:             0.1.0.0
synopsis:            Create artwork from satellite imagery.
description:         Create artwork from satellite imagery.
homepage:            https://github.com/fosskers/mapart
license:             BSD3
author:              Ross Bernet, Colin Woodbury, Nathan Zimmerman
maintainer:          colingw@gmail.com
copyright:           2017 ???
category:            Web

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Odph
  - -threaded

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 0.11 && < 1.3
  - bytestring
  - containers
  - JuicyPixels >= 3.2 && < 3.3
  - lucid >= 2.9 && < 3.0
  - mapalgebra < 1.0
  - servant >= 0.9 && < 0.12
  - servant-lucid >= 0.7 && < 0.8
  - servant-server >= 0.9 && < 0.12
  - servant-JuicyPixels >= 0.3 && < 0.4
  - unix
  - warp >= 3.2 && < 3.3

executables:
  server:
    main: Server.hs
