resolver: lts-9.3

packages:
  - location: '.'
  - location:
      git: git@github.com:fosskers/mapalgebra
      commit: c6ce7349042332c84acb834c78b4143e7c78aec1
    extra-dep: true


extra-deps:
  - repa-3.4.1.3
  - floating-bits-0.3.0.0

flags: {}

extra-package-dbs: []
